name: teledoc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  
  flutter_gradient_colors:
  uuid: 
  introduction_screen: 
  pin_code_fields: 
  flutter_custom_clippers:
  image_picker:
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  jitsi_meet: ^4.0.0
  flutter_svg: ^0.22.0
  path_provider: ^2.0.2
  google_maps_flutter: ^2.0.6
  firebase_storage: ^10.0.1
  flutter_custom_dialog: ^1.0.20
  geolocator: ^7.4.0
  geocoder: ^0.2.1
  geocoding: ^2.0.0
  random_string: ^2.3.1
  stream_chat_flutter: ^2.1.2
  http: ^0.13.3
  bubble_tab_indicator: ^0.1.6
  carousel_slider: ^4.0.0
  webview_flutter: ^2.0.12
  flutter_riverpod: ^0.14.0+3
  page_transition: ^2.0.2
  syncfusion_flutter_calendar: ^19.2.55
  provider: ^5.0.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  syncfusion_flutter_signaturepad: ^19.2.59
  syncfusion_flutter_pdf: ^19.2.59-beta
  open_file: ^3.2.1
  qr_code_scanner: ^0.5.2
  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^19.2.59
  flutter_ringtone_player: ^3.0.0
  favorite_button: ^0.0.4
  flutter_rating_bar: ^4.0.0
  flutter_firebase_chat_core: ^1.4.2
  flutter_chat_ui: ^1.4.1
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/my_logo.png
    - assets/images/im1.png
    - assets/images/im2.png
    - assets/images/im3.png
    - assets/images/im4.png
    - assets/images/im5.png
    - assets/images/im6.png
    - assets/images/on1.png
    - assets/images/on2.png
    - assets/images/log1.png
    - assets/images/log2.png
    - assets/images/gif1.gif
    - assets/images/gif2.gif
    - assets/images/gif3.gif
    - assets/images/gif5.gif
    - assets/images/gif6.gif
    - assets/images/re1.png
    - assets/images/re2.png
    - assets/images/test.png
    - assets/images/test2.png
    - assets/images/prof.png
    - assets/images/meet.png
    - assets/images/b.jpg
    - assets/images/modal.jpg
    - assets/images/marker.png
    - assets/images/doctor.png
    - assets/images/1.png
    - assets/images/markers.png
    - assets/images/mak.png
    - assets/images/ih.png
    - assets/images/it.png
    - assets/images/pratician.png
    - assets/images/camer.png
    - assets/images/Heath.png
    - assets/images/cov.png
    - assets/images/vaccinate.png
    - assets/images/top.jpeg
    
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
